package gameappl.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name="categories")
public class Category {

	// ==============
	// PRIVATE FIELDS
	// ==============
		
	// An autogenerated id (unique for each Category in the db)
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	 
	//Category name
	@Column(unique=true)
	@NotNull
	private String name;
	
	// ==============
	// PUBLIC METHODS
	
	// ==============
	/**
	 * Category constructor
	 * @param name
	 */
	public Category( String name) {
		super();
		
		this.name = name;
	}
	/**
	 * Default Constructor
	 */
	public Category() {
		super();
		
	}
    /**
     * @return Category id
     */
	public int getId() {
		return id;
	}
 
	/**
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}
    /**
     * @return name
     */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	
	
}
