package gameappl.domain;


import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An Entity Student Composed by seven fields (id,name,password,age,mail,gender,myscores).
 * The Entity annotation indicates that this class is a JPA entity.
 * @author Hussam
 */

@Entity
//table name in database
@Table(name="student")  
public class Student {
    
	// ==============
	// PRIVATE FIELDS
	// ==============
	
	// An autogenerated id (unique for each Student in the db)
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;     
	//Student name
	@NotNull
	private String name;
	//student password
	@NotNull
	private String password;
	
	//student age
	@NotNull
	private int age;
	//student mail
	@NotNull
	private String mail;
	//student gender
	@NotNull
	private String gender;
	//student score for each game
	private Set<ScoreDetail>myScores;
	
	/**
	 * student constructor
	 * @param student info  
	 */
	public Student(String name, String password, int age, String mail, String gender) {
		super();
		this.name = name;
		this.password = password;
		this.age = age;
		this.mail = mail;
		this.gender = gender;
	}

	// ==============
	// PUBLIC METHODS
	// ==============
	  
	
	/**
	 * Default Student Constructor 
	 */
	public Student() {
		super();
		
	}
	/**
	 * @return student id
	 */
	public int getId() {
		return id;
	}
	/**
	 * @param id The id to set
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * @return name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * @return password
	 */
	public String getPassword() {
		return password;
	}
	/**
	 *@param password The password to set 
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * @return age
	 */
	public int getAge() {
		return age;
	}
	/**
	 * @param age The age to set
	 */
	public void setAge(int age) {
		this.age = age;
	}
	/**
	 * @return mail
	 */
	public String getMail() {
		return mail;
	}
	/**
	 * @param mail The mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}
	/**
	 * @return gender
	 */
	public String getGender() {
		return gender;
	}
	/**
	 * @param gender
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	/*
	@OneToMany(mappedBy = "Student", cascade = CascadeType.ALL)
	public Set<ScoreDetail> getmyScore()
	{
		return myScores;
	}
	
	public void setmyScore(Set<ScoreDetail> scores)
	{
		this.myScores=scores;
	}
	
	/*@Override
	public String toString(){
		String result=String.format("Student[id=%d,name='%s',passwors='%s',age='%s',mail='%s',gender='%s']",
				id,name,password,age,mail,gender);
		if(myScores!=null)
		{
			for(ScoreDetail score:myScores)
			{
				result+=String.format("ScoreDetail[id=%d,name='%s',score=%d]",score.getId(),score.getGameName(),score.getScore() );
			}
		}
		return result;
	}
	*/
	
}//Student class
